# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-22 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Rating', models.FloatField()),
                ('Date', models.DateTimeField()),
                ('Feedback', models.TextField(max_length=300)),
            ],
        ),
    ]
