# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30)),
                ('Mobile', models.BigIntegerField()),
                ('Location', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'hyderabad'), ('che', 'chennai'), ('mum', 'mumbai'), ('ban', 'bangalore'), ('pune', 'pune')], max_length=30)),
                ('Course', multiselectfield.db.fields.MultiSelectField(choices=[('PYTHON', 'PYTHON'), ('DJANGO', 'DJANGO'), ('UI', 'UI'), ('REST-API', 'REST-API'), ('JAVA', 'JAVA')], max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
            ],
        ),
    ]
