# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-25 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_contactdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursesdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=30)),
                ('faculty_name', models.CharField(max_length=30)),
                ('faculty_ex', models.IntegerField()),
                ('course_fee', models.IntegerField()),
                ('course_duration', models.IntegerField()),
                ('starting_date', models.DateField(max_length=30)),
                ('starting_time', models.TimeField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PYTHON', 'PYTHON'), ('DJANGO', 'DJANGO'), ('UI', 'UI'), ('REST-API', 'REST-API')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Dob',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'hyderabad'), ('che', 'chennai'), ('mum', 'mumbai'), ('ban', 'bangalore'), ('pune', 'pune')], max_length=100),
        ),
    ]
